// This file will be generated by `dotnet ef migrations add InitialCreate`
// Placeholder for the actual content
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PositionReporting.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "TBL_CURRENCY",
                columns: table => new
                {
                    curr_code = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: false),
                    deciml = table.Column<int>(type: "int", nullable: false),
                    tts = table.Column<float>(type: "real", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TBL_CURRENCY", x => x.curr_code);
                });

            migrationBuilder.CreateTable(
                name: "DEPTLIST",
                columns: table => new
                {
                    deptcode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    deptdesc = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    closed_date = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    closed_by = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    status = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    REF_LOCK = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: false, defaultValue: ".")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DEPTLIST", x => x.deptcode);
                });

            migrationBuilder.CreateTable(
                name: "TBL_MISC",
                columns: table => new
                {
                    data01 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    dataid2 = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: false),
                    dataid1 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false, defaultValue: "NOSTRO"),
                    created_at = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TBL_MISC", x => new { x.data01, x.dataid2 });
                });

            migrationBuilder.CreateTable(
                name: "MAINTABLE",
                columns: table => new
                {
                    uid = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    dept = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    ttype = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    posref = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    trans_date = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    value_date = table.Column<DateTime>(type: "date", nullable: false),
                    issue_date = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    their_ref = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    reference = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    dr_acct = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    dr_acctname = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    dr_cur = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: false),
                    dr_amount = table.Column<float>(type: "real", nullable: false),
                    cr_acct = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    cr_acctname = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    cr_cur = table.Column<string>(type: "nvarchar(3)", maxLength: 3, nullable: false),
                    cr_amount = table.Column<float>(type: "real", nullable: false),
                    calc = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: false),
                    rate = table.Column<float>(type: "real", nullable: false),
                    status = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: false),
                    maker_id = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    checker_id = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    correction_date = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    checkout = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: true),
                    checked_date = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MAINTABLE", x => x.uid);
                });

            migrationBuilder.CreateTable(
                name: "TBL_USER",
                columns: table => new
                {
                    uid = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    userid = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    email = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    dept = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    accessmask = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    pwd = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    is_active = table.Column<bool>(type: "bit", nullable: false, defaultValue: true),
                    created_at = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TBL_USER", x => x.uid);
                });

            migrationBuilder.CreateTable(
                name: "TBL_REFRESH_TOKEN",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    TokenHash = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    UserId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ExpiresAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    IsRevoked = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    ReplacedByTokenHash = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    CreatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    UpdatedAt = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TBL_REFRESH_TOKEN", x => x.Id);
                    table.ForeignKey(
                        name: "FK_TBL_REFRESH_TOKEN_TBL_USER_UserId",
                        column: x => x.UserId,
                        principalTable: "TBL_USER",
                        principalColumn: "uid",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "TBL_CURRENCY",
                columns: new[] { "curr_code", "created_at", "deciml", "tts", "updated_at" },
                values: new object[,]
                {
                    { "JPY", new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 0, 0.009f, null },
                    { "SGD", new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 2, 1f, null },
                    { "USD", new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 2, 1.35f, null }
                });

            migrationBuilder.InsertData(
                table: "DEPTLIST",
                columns: new[] { "deptcode", "closed_by", "closed_date", "created_at", "deptdesc", "status", "updated_at" },
                values: new object[,]
                {
                    { "ADM", null, null, new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), "Administration", "OPEN", null },
                    { "FN", null, null, new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), "Finance Department", "OPEN", null },
                    { "OPS", null, null, new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), "Operations Department", "OPEN", null }
                });

            migrationBuilder.InsertData(
                table: "TBL_MISC",
                columns: new[] { "data01", "dataid2", "created_at", "updated_at" },
                values: new object[,]
                {
                    { "SGDBNK001", "SGD", new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), null },
                    { "USDBNK001", "USD", new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), null }
                });

            migrationBuilder.InsertData(
                table: "TBL_USER",
                columns: new[] { "uid", "accessmask", "created_at", "dept", "email", "updated_at", "userid" },
                values: new object[,]
                {
                    { new Guid("b8d2e7c1-f8a6-4b2d-9d2e-7c1f8a6b4d3d"), "1100010", new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), "FN", "user1@yourorg.com", null, "DOMAIN\\USER1" },
                    { new Guid("c5e6a3b9-2e8b-4b2d-9d2e-7c1f8a6b4d3c"), "1111111", new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), "ADM", "admin@yourorg.com", null, "DOMAIN\\ADMIN" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_MAINTABLE_dept",
                table: "MAINTABLE",
                column: "dept");

            migrationBuilder.CreateIndex(
                name: "IX_MAINTABLE_maker_id",
                table: "MAINTABLE",
                column: "maker_id");

            migrationBuilder.CreateIndex(
                name: "IX_MAINTABLE_status",
                table: "MAINTABLE",
                column: "status");

            migrationBuilder.CreateIndex(
                name: "IX_MAINTABLE_value_date",
                table: "MAINTABLE",
                column: "value_date");

            migrationBuilder.CreateIndex(
                name: "IX_TBL_REFRESH_TOKEN_TokenHash",
                table: "TBL_REFRESH_TOKEN",
                column: "TokenHash",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_TBL_REFRESH_TOKEN_UserId",
                table: "TBL_REFRESH_TOKEN",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_TBL_USER_userid",
                table: "TBL_USER",
                column: "userid",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "TBL_CURRENCY");

            migrationBuilder.DropTable(
                name: "DEPTLIST");

            migrationBuilder.DropTable(
                name: "TBL_MISC");

            migrationBuilder.DropTable(
                name: "MAINTABLE");

            migrationBuilder.DropTable(
                name: "TBL_REFRESH_TOKEN");

            migrationBuilder.DropTable(
                name: "TBL_USER");
        }
    }
}