// This file will be generated by `dotnet ef migrations add InitialCreate`
// Placeholder for the actual content

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PositionReporting.Infrastructure.Data;
using System;

#nullable disable

namespace PositionReporting.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PositionReporting.Infrastructure.Data.Entities.Currency", b =>
                {
                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnName("curr_code")
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DecimalPrecision")
                        .HasColumnName("deciml")
                        .HasColumnType("int");

                    b.Property<float>("ExchangeRateTTS")
                        .HasColumnName("tts")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnName("updated_at")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CurrencyCode");

                    b.ToTable("TBL_CURRENCY", (string)null);

                    b.HasData(
                        new
                        {
                            CurrencyCode = "SGD",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DecimalPrecision = 2,
                            ExchangeRateTTS = 1f
                        },
                        new
                        {
                            CurrencyCode = "USD",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DecimalPrecision = 2,
                            ExchangeRateTTS = 1.35f
                        },
                        new
                        {
                            CurrencyCode = "JPY",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DecimalPrecision = 0,
                            ExchangeRateTTS = 0.009f
                        });
                });

            modelBuilder.Entity("PositionReporting.Infrastructure.Data.Entities.Department", b =>
                {
                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(10)
                        .HasColumnName("deptcode")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(100)
                        .HasColumnName("closed_by")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("ClosedDate")
                        .HasColumnName("closed_date")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DepartmentDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnName("deptdesc")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RefLock")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(".")
                        .HasMaxLength(1)
                        .HasColumnName("REF_LOCK")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnName("status")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnName("updated_at")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("DepartmentCode");

                    b.ToTable("DEPTLIST", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentCode = "FN",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentDescription = "Finance Department",
                            Status = "OPEN"
                        },
                        new
                        {
                            DepartmentCode = "OPS",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentDescription = "Operations Department",
                            Status = "OPEN"
                        },
                        new
                        {
                            DepartmentCode = "ADM",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentDescription = "Administration",
                            Status = "OPEN"
                        });
                });

            modelBuilder.Entity("PositionReporting.Infrastructure.Data.Entities.NostroAccount", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnName("data01")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnName("dataid2")
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DataId1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("NOSTRO")
                        .HasMaxLength(50)
                        .HasColumnName("dataid1")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnName("updated_at")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AccountNumber", "CurrencyCode");

                    b.ToTable("TBL_MISC", (string)null);

                    b.HasData(
                        new
                        {
                            AccountNumber = "SGDBNK001",
                            CurrencyCode = "SGD",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataId1 = "NOSTRO"
                        },
                        new
                        {
                            AccountNumber = "USDBNK001",
                            CurrencyCode = "USD",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataId1 = "NOSTRO"
                        });
                });

            modelBuilder.Entity("PositionReporting.Infrastructure.Data.Entities.PositionEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnName("uid")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ApprovedDate")
                        .HasColumnName("checked_date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CalculationSymbol")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnName("calc")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("CheckerId")
                        .HasMaxLength(100)
                        .HasColumnName("checker_id")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CheckoutId")
                        .HasMaxLength(150)
                        .HasColumnName("checkout")
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("CorrectionDate")
                        .HasColumnName("correction_date")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreditAccount")
                        .HasMaxLength(50)
                        .HasColumnName("cr_acct")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreditAccountName")
                        .HasMaxLength(100)
                        .HasColumnName("cr_acctname")
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("CreditAmount")
                        .HasColumnType("real")
                        .HasColumnName("cr_amount");

                    b.Property<string>("CreditCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnName("cr_cur")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DebitAccount")
                        .HasMaxLength(50)
                        .HasColumnName("dr_acct")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DebitAccountName")
                        .HasMaxLength(100)
                        .HasColumnName("dr_acctname")
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("DebitAmount")
                        .HasColumnType("real")
                        .HasColumnName("dr_amount");

                    b.Property<string>("DebitCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnName("dr_cur")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnName("dept")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset?>("EntryDate")
                        .HasColumnName("trans_date")
                        .HasColumnType("datetimeoffset");

                    b.Property<float>("ExchangeRate")
                        .HasColumnType("real")
                        .HasColumnName("rate");

                    b.Property<DateTimeOffset?>("IssueDate")
                        .HasColumnName("issue_date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MakerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnName("maker_id")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnName("reference")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(20)
                        .HasColumnName("posref")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnName("status")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TheirReference")
                        .HasMaxLength(200)
                        .HasColumnName("their_ref")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnName("ttype")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnName("updated_at")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MakerId");

                    b.HasIndex("Status");

                    b.HasIndex("ValueDate");

                    b.ToTable("MAINTABLE", (string)null);
                });

            modelBuilder.Entity("PositionReporting.Infrastructure.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false)
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("TBL_REFRESH_TOKEN", (string)null);
                });

            modelBuilder.Entity("PositionReporting.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessMask")
                        .HasMaxLength(20)
                        .HasColumnName("accessmask")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DepartmentId")
                        .HasMaxLength(10)
                        .HasColumnName("dept")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnName("email")
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true)
                        .HasColumnName("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnName("pwd")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnName("updated_at")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnName("userid")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TBL_USER", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5e6a3b9-2e8b-4b2d-9d2e-7c1f8a6b4d3c"),
                            AccessMask = "1111111",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = "ADM",
                            Email = "admin@yourorg.com",
                            IsActive = true,
                            UserId = "DOMAIN\\ADMIN"
                        },
                        new
                        {
                            Id = new Guid("b8d2e7c1-f8a6-4b2d-9d2e-7c1f8a6b4d3d"),
                            AccessMask = "1100010",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = "FN",
                            Email = "user1@yourorg.com",
                            IsActive = true,
                            UserId = "DOMAIN\\USER1"
                        });
                });

            modelBuilder.Entity("PositionReporting.Infrastructure.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("PositionReporting.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}