using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ProjectName.Domain.Enums;
using ProjectName.Infrastructure.Data.Entities;

namespace ProjectName.Infrastructure.Data.Configuration
{
    public class PositionReportConfiguration : IEntityTypeConfiguration<PositionReport>
    {
        public void Configure(EntityTypeBuilder<PositionReport> builder)
        {
            builder.ToTable("position_reports");

            builder.HasKey(pr => pr.Uid);
            builder.Property(pr => pr.Uid)
                .HasColumnName("uid")
                .HasDefaultValueSql("gen_random_uuid()")
                .IsRequired();

            builder.Property(pr => pr.Dept)
                .HasColumnName("dept")
                .HasMaxLength(10)
                .IsRequired();

            builder.Property(pr => pr.Type)
                .HasColumnName("ttype")
                .HasConversion<string>() // Store enum as string
                .HasMaxLength(10)
                .IsRequired();

            builder.Property(pr => pr.DrAcct)
                .HasColumnName("dr_acct")
                .HasMaxLength(20)
                .IsRequired();

            builder.Property(pr => pr.DrAcctName)
                .HasColumnName("dr_acctname")
                .HasMaxLength(100)
                .IsRequired();

            builder.Property(pr => pr.DrCur)
                .HasColumnName("dr_cur")
                .HasMaxLength(3)
                .IsRequired();

            builder.Property(pr => pr.DrAmount)
                .HasColumnName("dr_amount")
                .HasColumnType("numeric(18,2)")
                .IsRequired();

            builder.Property(pr => pr.CrAcct)
                .HasColumnName("cr_acct")
                .HasMaxLength(20)
                .IsRequired();

            builder.Property(pr => pr.CrAcctName)
                .HasColumnName("cr_acctname")
                .HasMaxLength(100)
                .IsRequired();

            builder.Property(pr => pr.CrCur)
                .HasColumnName("cr_cur")
                .HasMaxLength(3)
                .IsRequired();

            builder.Property(pr => pr.CrAmount)
                .HasColumnName("cr_amount")
                .HasColumnType("numeric(18,2)")
                .IsRequired();

            builder.Property(pr => pr.Calc)
                .HasColumnName("calc")
                .HasMaxLength(1)
                .IsRequired(); // e.g., '*' or '/'

            builder.Property(pr => pr.Rate)
                .HasColumnName("rate")
                .HasColumnType("numeric(18,4)") // Rates can have more decimals
                .IsRequired();

            builder.Property(pr => pr.TransDate)
                .HasColumnName("trans_date")
                .IsRequired();

            builder.Property(pr => pr.ValueDate)
                .HasColumnName("value_date")
                .IsRequired();

            builder.Property(pr => pr.IssueDate)
                .HasColumnName("issue_date")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .IsRequired();

            builder.Property(pr => pr.TheirRef)
                .HasColumnName("their_ref")
                .HasMaxLength(200);

            builder.Property(pr => pr.Reference)
                .HasColumnName("reference")
                .HasMaxLength(200)
                .IsRequired();

            builder.Property(pr => pr.Status)
                .HasColumnName("status")
                .HasConversion<char>() // Store enum as char
                .HasMaxLength(1)
                .IsRequired();

            builder.Property(pr => pr.MakerId)
                .HasColumnName("maker_id")
                .HasMaxLength(100)
                .IsRequired();

            builder.Property(pr => pr.CheckerId)
                .HasColumnName("checker_id")
                .HasMaxLength(100);

            builder.Property(pr => pr.PosRef)
                .HasColumnName("posref")
                .HasMaxLength(50); // Position reference number generated by system

            builder.Property(pr => pr.Checkout)
                .HasColumnName("checkout")
                .HasMaxLength(150); // Contains UserID.SessionID

            builder.Property(pr => pr.CheckoutSessionId)
                .HasColumnName("checkout_session_id")
                .HasMaxLength(10); // Stores just the 10-char session ID

            builder.Property(pr => pr.CorrectionDate)
                .HasColumnName("correction_date");

            builder.Property(pr => pr.CorrectionId)
                .HasColumnName("correction_id")
                .HasMaxLength(100);

            builder.Property(pr => pr.CheckedDate)
                .HasColumnName("checked_date"); // This is edtAPPROVEDATE from Delphi

            // Indexes for frequently queried columns
            builder.HasIndex(pr => pr.Dept);
            builder.HasIndex(pr => pr.Status);
            builder.HasIndex(pr => pr.TransDate);
            builder.HasIndex(pr => pr.ValueDate);
            builder.HasIndex(pr => pr.MakerId);
            builder.HasIndex(pr => pr.Checkout);
        }
    }
}